### ISSUE TITLE
苹果手机上不能正常使用plus.nativeUI.toast('', {type:'richtext'})

### ISSUE THREAD

**Issue by baoyinan** [smalltee/DuduBook#69]
使用plus.nativeUI.toast('<span>'+msg+'</span>', {type:'richtext'})来去除hbuilder的关键字后，在苹果手机上发现无法正常显示提示消息

**Comment by smalltee** [comment]
Not exist. close it

**Comment by smalltee** [comment]
Done. Keep it, hbuilder will be the app name
